# synthetic-package: false
# при выполнении pub get ругается на отсутствие данной строчки
arb-dir: lib/core/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations