name: Flutter PR
on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "drz-swagger/**"
      - ".vscode/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: stable
      - run: echo "AIML_API_KEY=${{ secrets.AIML_API_KEY }}" > .env
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: Apk Release
          path: build/app/outputs/apk/release/app-release.apk




